# Generated by Django 5.1 on 2024-08-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0003_alter_person_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
