# Generated by Django 5.0.4 on 2024-05-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0003_alter_person_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='my_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_auth.classroom'),
        ),
    ]
