# Generated by Django 5.1 on 2024-08-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0004_alter_person_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_status',
            field=models.BooleanField(default=False),
        ),
    ]
