# Generated by Django 5.0.4 on 2024-05-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0004_alter_person_my_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
