# Generated by Django 5.1 on 2024-08-20 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0005_person_profile_status'),
        ('usertasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('item_id', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('message', 'Message'), ('Notification', 'Notification'), ('task', 'Task')], default='None', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_auth.person')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
