# Generated by Django 5.1 on 2024-08-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
