# Generated by Django 5.0.4 on 2024-05-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcompletion',
            name='is_done',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread'), ('replied', 'Replied'), ('sent', 'Sent')], default='sent', max_length=15),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('uncompleted', 'Uncompleted'), ('upcoming', 'Upcoming')], default='sent', max_length=15),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('uncompleted', 'Uncompleted'), ('upcoming', 'Upcoming')], default='sent', max_length=15),
        ),
    ]
