# Generated by Django 5.0.4 on 2024-05-16 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('users_auth', '0005_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread'), ('replied', 'Replied')], default='unread', max_length=15),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread'), ('replied', 'Replied')], default='unread', max_length=15),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('post_body', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='post_pics/')),
                ('media', models.FileField(blank=True, null=True, upload_to='audio_files/')),
                ('status', models.CharField(choices=[('read', 'Read'), ('unread', 'Unread'), ('replied', 'Replied')], default='unread', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='users_auth.person')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
