# Generated by Django 5.1 on 2024-08-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_message_options_remove_message_responce_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.AddField(
            model_name='message',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
